CREATE TABLE audio_assets (
    id uuid PRIMARY KEY,
    recording_id uuid NOT NULL UNIQUE,
    source_provider text NOT NULL,
    source_reference text,
    generation integer NOT NULL DEFAULT 0,
    original_object_key text,
    playable_object_key text,
    codec text,
    container text,
    bitrate integer,
    sample_rate integer,
    channels integer,
    duration_ms integer,
    size_bytes bigint,
    checksum text,
    status text NOT NULL,
    last_error text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL,
    CONSTRAINT audio_assets_status_known CHECK (status IN ('PENDING', 'ACQUIRING', 'PROCESSING', 'READY', 'FAILED')),
    CONSTRAINT audio_assets_provider_not_empty CHECK (char_length(source_provider) > 0),
    CONSTRAINT audio_assets_reference_not_empty CHECK (source_reference IS NULL OR char_length(source_reference) > 0),
    CONSTRAINT audio_assets_generation_non_negative CHECK (generation >= 0),
    CONSTRAINT audio_assets_original_key_not_empty CHECK (original_object_key IS NULL OR char_length(original_object_key) > 0),
    CONSTRAINT audio_assets_playable_key_not_empty CHECK (playable_object_key IS NULL OR char_length(playable_object_key) > 0),
    CONSTRAINT audio_assets_codec_not_empty CHECK (codec IS NULL OR char_length(codec) > 0),
    CONSTRAINT audio_assets_container_not_empty CHECK (container IS NULL OR char_length(container) > 0),
    CONSTRAINT audio_assets_bitrate_non_negative CHECK (bitrate IS NULL OR bitrate >= 0),
    CONSTRAINT audio_assets_sample_rate_non_negative CHECK (sample_rate IS NULL OR sample_rate >= 0),
    CONSTRAINT audio_assets_channels_non_negative CHECK (channels IS NULL OR channels >= 0),
    CONSTRAINT audio_assets_duration_non_negative CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT audio_assets_size_non_negative CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT audio_assets_checksum_not_empty CHECK (checksum IS NULL OR char_length(checksum) > 0),
    CONSTRAINT audio_assets_last_error_not_empty CHECK (last_error IS NULL OR char_length(last_error) > 0)
);
